repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'npm run lint --prefix frontend/app || true'
        language: system
        files: ^frontend/app/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false
        verbose: true
      - id: tsc
        name: tsc
        entry: bash -c 'cd frontend/app && npx tsc -b --noEmit || true'
        language: system
        files: ^frontend/app/.*\.(ts|tsx)$
        pass_filenames: false
        verbose: true
