services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
