from pathlib import Path
from typing import Any

class Page:
    def get_text(self, *args: Any, **kwargs: Any) -> str: ...

class Document:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Page: ...
    def close(self) -> None: ...

def open(path: str | Path, *args: Any, **kwargs: Any) -> Document: ...
