"""Structural storage contracts for repo-level provider parity."""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal, Protocol

from pydantic import BaseModel

NotificationType = Literal["steer", "command", "agent", "chat"]


# ---------------------------------------------------------------------------
# Sandbox — repo protocols
# ---------------------------------------------------------------------------


class LeaseRepo(Protocol):
    """Sandbox lease CRUD. Returns raw dicts — domain object construction is the consumer's job."""

    def close(self) -> None: ...
    def get(self, lease_id: str) -> dict[str, Any] | None: ...
    def create(self, lease_id: str, provider_name: str, volume_id: str | None = None) -> dict[str, Any]: ...
    def find_by_instance(self, *, provider_name: str, instance_id: str) -> dict[str, Any] | None: ...
    def adopt_instance(self, *, lease_id: str, provider_name: str, instance_id: str, status: str = "unknown") -> dict[str, Any]: ...
    def mark_needs_refresh(self, lease_id: str, hint_at: Any = None) -> bool: ...
    def delete(self, lease_id: str) -> None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def list_by_provider(self, provider_name: str) -> list[dict[str, Any]]: ...


class TerminalRepo(Protocol):
    """Abstract terminal CRUD + thread pointer management."""

    def close(self) -> None: ...
    def get_active(self, thread_id: str) -> dict[str, Any] | None: ...
    def get_default(self, thread_id: str) -> dict[str, Any] | None: ...
    def get_by_id(self, terminal_id: str) -> dict[str, Any] | None: ...
    def get_latest_by_lease(self, lease_id: str) -> dict[str, Any] | None: ...
    def get_timestamps(self, terminal_id: str) -> tuple[str | None, str | None]: ...
    def list_by_thread(self, thread_id: str) -> list[dict[str, Any]]: ...
    def create(self, terminal_id: str, thread_id: str, lease_id: str, initial_cwd: str = "/root") -> dict[str, Any]: ...
    def set_active(self, thread_id: str, terminal_id: str) -> None: ...
    def delete_by_thread(self, thread_id: str) -> None: ...
    def delete(self, terminal_id: str) -> None: ...
    def list_all(self) -> list[dict[str, Any]]: ...


class ProviderEventRepo(Protocol):
    """Webhook event persistence."""

    def close(self) -> None: ...
    def record(
        self,
        *,
        provider_name: str,
        instance_id: str,
        event_type: str,
        payload: dict[str, Any],
        matched_lease_id: str | None,
    ) -> None: ...
    def list_recent(self, limit: int = 100) -> list[dict[str, Any]]: ...


class ChatSessionRepo(Protocol):
    """Chat session + terminal command persistence."""

    def close(self) -> None: ...
    def ensure_tables(self) -> None: ...
    def create_session(
        self,
        session_id: str,
        thread_id: str,
        terminal_id: str,
        lease_id: str,
        *,
        runtime_id: str | None = None,
        status: str = "active",
        idle_ttl_sec: int = 600,
        max_duration_sec: int = 86400,
        budget_json: str | None = None,
        started_at: str | None = None,
        last_active_at: str | None = None,
    ) -> dict[str, Any]: ...
    def get_session(self, thread_id: str, terminal_id: str | None = None) -> dict[str, Any] | None: ...
    def get_session_by_id(self, session_id: str) -> dict[str, Any] | None: ...
    def get_session_policy(self, session_id: str) -> dict[str, Any] | None: ...
    def load_status(self, session_id: str) -> str | None: ...
    def touch(self, session_id: str, last_active_at: str | None = None, status: str | None = None) -> None: ...
    def touch_thread_activity(self, thread_id: str, last_active_at: str | None = None) -> None: ...
    def pause(self, session_id: str) -> None: ...
    def resume(self, session_id: str) -> None: ...
    def delete_session(self, session_id: str, *, reason: str = "closed") -> None: ...
    def delete_by_thread(self, thread_id: str) -> None: ...
    def terminal_has_running_command(self, terminal_id: str) -> bool: ...
    def lease_has_running_command(self, lease_id: str) -> bool: ...
    def list_active(self) -> list[dict[str, Any]]: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def cleanup_expired(self) -> list[str]: ...


# ---------------------------------------------------------------------------
# Member-Chat — enums + row types
# ---------------------------------------------------------------------------


class MemberType(StrEnum):
    HUMAN = "human"
    MYCEL_AGENT = "mycel_agent"
    OPENCLAW_AGENT = "openclaw_agent"


class MemberRow(BaseModel):
    id: str
    name: str
    type: MemberType
    avatar: str | None = None
    description: str | None = None
    config_dir: str | None = None
    owner_user_id: str | None = None
    next_entity_seq: int = 0
    created_at: float
    updated_at: float | None = None
    email: str | None = None
    mycel_id: int | None = None


class ChatRow(BaseModel):
    id: str
    title: str | None = None
    status: str = "active"
    created_at: float
    updated_at: float | None = None


# ---------------------------------------------------------------------------
# Delivery strategy — contact relationships + delivery actions
# ---------------------------------------------------------------------------


class DeliveryAction(StrEnum):
    """What to do when a chat message reaches a recipient."""

    DELIVER = "deliver"  # full delivery: inject into agent context, wake agent
    NOTIFY = "notify"  # red dot only: message stored, unread counted, no delivery
    DROP = "drop"  # silent: message stored but invisible to this user


ContactRelation = Literal["normal", "blocked", "muted"]


class ContactRow(BaseModel):
    """Directional relationship between two social identities. A→B independent of B→A."""

    owner_id: str  # social identity: user_id for humans, member_id for agents
    target_id: str  # social identity: user_id for humans, member_id for agents
    relation: ContactRelation
    created_at: float
    updated_at: float | None = None


class CheckpointRepo(Protocol):
    def close(self) -> None: ...
    def list_thread_ids(self) -> list[str]: ...
    def delete_thread_data(self, thread_id: str) -> None: ...
    def delete_checkpoints_by_ids(self, thread_id: str, checkpoint_ids: list[str]) -> None: ...


class RunEventRepo(Protocol):
    def close(self) -> None: ...
    def append_event(
        self,
        thread_id: str,
        run_id: str,
        event_type: str,
        data: dict[str, Any],
        message_id: str | None = None,
    ) -> int: ...
    def list_events(
        self,
        thread_id: str,
        run_id: str,
        *,
        after: int = 0,
        limit: int = 200,
    ) -> list[dict[str, Any]]: ...
    def latest_seq(self, thread_id: str) -> int: ...
    def latest_run_id(self, thread_id: str) -> str | None: ...
    def list_run_ids(self, thread_id: str) -> list[str]: ...
    def run_start_seq(self, thread_id: str, run_id: str) -> int: ...
    def delete_runs(self, thread_id: str, run_ids: list[str]) -> int: ...
    def delete_thread_events(self, thread_id: str) -> int: ...


class RecipeRepo(Protocol):
    def close(self) -> None: ...
    def list_by_owner(self, owner_user_id: str) -> list[dict[str, Any]]: ...
    def get(self, owner_user_id: str, recipe_id: str) -> dict[str, Any] | None: ...
    def upsert(
        self,
        *,
        owner_user_id: str,
        recipe_id: str,
        kind: str,
        provider_type: str,
        data: dict[str, Any],
        created_at: int | None = None,
    ) -> dict[str, Any]: ...
    def delete(self, owner_user_id: str, recipe_id: str) -> bool: ...
    def delete_thread_events(self, thread_id: str) -> int: ...


class ThreadLaunchPrefRepo(Protocol):
    def close(self) -> None: ...
    def get(self, owner_user_id: str, member_id: str) -> dict[str, Any] | None: ...
    def save_confirmed(self, owner_user_id: str, member_id: str, config: dict[str, Any]) -> None: ...
    def save_successful(self, owner_user_id: str, member_id: str, config: dict[str, Any]) -> None: ...


class UserSettingsRepo(Protocol):
    def close(self) -> None: ...
    def get(self, user_id: str) -> dict[str, Any]: ...
    def set_default_workspace(self, user_id: str, workspace: str) -> None: ...
    def add_recent_workspace(self, user_id: str, workspace: str) -> None: ...
    def set_default_model(self, user_id: str, model: str) -> None: ...
    def get_models_config(self, user_id: str) -> dict[str, Any] | None: ...
    def set_models_config(self, user_id: str, config: dict[str, Any]) -> None: ...
    def get_observation_config(self, user_id: str) -> dict[str, Any] | None: ...
    def set_observation_config(self, user_id: str, config: dict[str, Any]) -> None: ...
    def get_sandbox_configs(self, user_id: str) -> dict[str, Any] | None: ...
    def set_sandbox_configs(self, user_id: str, configs: dict[str, Any]) -> None: ...


class AgentConfigRepo(Protocol):
    def close(self) -> None: ...
    def get_config(self, member_id: str) -> dict[str, Any] | None: ...
    def save_config(self, member_id: str, data: dict[str, Any]) -> None: ...
    def delete_config(self, member_id: str) -> None: ...
    def list_rules(self, member_id: str) -> list[dict[str, Any]]: ...
    def save_rule(self, member_id: str, filename: str, content: str, rule_id: str | None = None) -> dict[str, Any]: ...
    def delete_rule(self, rule_id: str) -> None: ...
    def list_skills(self, member_id: str) -> list[dict[str, Any]]: ...
    def save_skill(
        self,
        member_id: str,
        name: str,
        content: str,
        meta: dict[str, Any] | None = None,
        skill_id: str | None = None,
    ) -> dict[str, Any]: ...
    def delete_skill(self, skill_id: str) -> None: ...
    def list_sub_agents(self, member_id: str) -> list[dict[str, Any]]: ...
    def save_sub_agent(
        self,
        member_id: str,
        name: str,
        *,
        description: str | None = None,
        model: str | None = None,
        tools: list[Any] | None = None,
        system_prompt: str | None = None,
        sub_agent_id: str | None = None,
    ) -> dict[str, Any]: ...
    def delete_sub_agent(self, sub_agent_id: str) -> None: ...


class PanelTaskRepo(Protocol):
    def close(self) -> None: ...
    def list_all(self, owner_user_id: str | None = None) -> list[dict[str, Any]]: ...
    def get(self, task_id: str, owner_user_id: str | None = None) -> dict[str, Any] | None: ...
    def get_highest_priority_pending(self, owner_user_id: str | None = None) -> dict[str, Any] | None: ...
    def create(self, **fields: Any) -> dict[str, Any]: ...
    def update(self, task_id: str, owner_user_id: str | None = None, **fields: Any) -> dict[str, Any] | None: ...
    def delete(self, task_id: str, owner_user_id: str | None = None) -> bool: ...
    def bulk_delete(self, ids: list[str], owner_user_id: str | None = None) -> int: ...
    def bulk_update_status(self, ids: list[str], status: str, owner_user_id: str | None = None) -> int: ...


class CronJobRepo(Protocol):
    def close(self) -> None: ...
    def list_all(self, owner_user_id: str | None = None) -> list[dict[str, Any]]: ...
    def get(self, job_id: str, owner_user_id: str | None = None) -> dict[str, Any] | None: ...
    def create(self, *, name: str, cron_expression: str, **fields: Any) -> dict[str, Any]: ...
    def update(self, job_id: str, owner_user_id: str | None = None, **fields: Any) -> dict[str, Any] | None: ...
    def delete(self, job_id: str, owner_user_id: str | None = None) -> bool: ...
    def list_enabled(self, owner_user_id: str | None = None) -> list[dict[str, Any]]: ...


class AgentRegistryRepo(Protocol):
    def close(self) -> None: ...
    def register(
        self,
        *,
        agent_id: str,
        name: str,
        thread_id: str,
        status: str,
        parent_agent_id: str | None,
        subagent_type: str | None,
    ) -> None: ...
    def get_by_id(self, agent_id: str) -> tuple[Any, ...] | None: ...
    def list_running_by_name(self, name: str) -> list[tuple[Any, ...]]: ...
    def update_status(self, agent_id: str, status: str) -> None: ...
    def get_latest_by_name_and_parent(self, name: str, parent_agent_id: str | None) -> tuple[Any, ...] | None: ...
    def list_running(self) -> list[tuple[Any, ...]]: ...


class ToolTaskRepo(Protocol):
    def close(self) -> None: ...
    def next_id(self, thread_id: str) -> str: ...
    def get(self, thread_id: str, task_id: str) -> Any | None: ...
    def list_all(self, thread_id: str) -> list[Any]: ...
    def insert(self, thread_id: str, task: Any) -> None: ...
    def update(self, thread_id: str, task: Any) -> None: ...
    def delete(self, thread_id: str, task_id: str) -> None: ...


class SyncFileRepo(Protocol):
    def close(self) -> None: ...
    def track_file(self, thread_id: str, relative_path: str, checksum: str, timestamp: int) -> None: ...
    def track_files_batch(self, thread_id: str, file_records: list[tuple[str, str, int]]) -> None: ...
    def get_file_info(self, thread_id: str, relative_path: str) -> dict[str, Any] | None: ...
    def get_all_files(self, thread_id: str) -> dict[str, str]: ...
    def clear_thread(self, thread_id: str) -> int: ...


class ResourceSnapshotRepo(Protocol):
    def close(self) -> None: ...
    def upsert_lease_resource_snapshot(self, **kwargs: Any) -> None: ...
    def list_snapshots_by_lease_ids(self, lease_ids: list[str]) -> dict[str, dict[str, Any]]: ...


class FileOperationRepo(Protocol):
    def close(self) -> None: ...
    def record(
        self,
        thread_id: str,
        checkpoint_id: str,
        operation_type: str,
        file_path: str,
        before_content: str | None,
        after_content: str,
        changes: list[dict] | None = None,
    ) -> str: ...
    def get_operations_for_thread(self, thread_id: str, status: str = "applied") -> list[Any]: ...
    def get_operations_after_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def get_operations_between_checkpoints(
        self,
        thread_id: str,
        from_checkpoint_id: str,
        to_checkpoint_id: str,
    ) -> list[Any]: ...
    def get_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def count_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> int: ...
    def mark_reverted(self, operation_ids: list[str]) -> None: ...
    def delete_thread_operations(self, thread_id: str) -> int: ...


# @@@summary-row-contract - standardize summary row payload as dict to keep provider parity explicit for static type checks.
type SummaryRow = dict[str, Any]


class SummaryRepo(Protocol):
    def ensure_tables(self) -> None: ...
    def save_summary(
        self,
        summary_id: str,
        thread_id: str,
        summary_text: str,
        compact_up_to_index: int,
        compacted_at: int,
        is_split_turn: bool,
        split_turn_prefix: str | None,
        created_at: str,
    ) -> None: ...
    def get_latest_summary_row(self, thread_id: str) -> SummaryRow | None: ...
    def list_summaries(self, thread_id: str) -> list[dict[str, object]]: ...
    def delete_thread_summaries(self, thread_id: str) -> None: ...
    def close(self) -> None: ...


class QueueItem(BaseModel):
    """A dequeued message with its notification type."""

    content: str
    notification_type: NotificationType
    source: str | None = None  # "owner" | "external" | "system"
    sender_id: str | None = None  # social identity: user_id for humans, member_id for agents
    sender_name: str | None = None
    sender_avatar_url: str | None = None
    is_steer: bool = False


class QueueRepo(Protocol):
    def close(self) -> None: ...
    def enqueue(
        self,
        thread_id: str,
        content: str,
        notification_type: NotificationType = "steer",
        source: str | None = None,
        sender_id: str | None = None,
        sender_name: str | None = None,
    ) -> None: ...
    def dequeue(self, thread_id: str) -> QueueItem | None: ...
    def drain_all(self, thread_id: str) -> list[QueueItem]: ...
    def peek(self, thread_id: str) -> bool: ...
    def list_queue(self, thread_id: str) -> list[dict[str, Any]]: ...
    def clear_queue(self, thread_id: str) -> None: ...
    def count(self, thread_id: str) -> int: ...


class SandboxVolumeRepo(Protocol):
    """Sandbox volume metadata. Stores serialized VolumeSource per lease."""

    def close(self) -> None: ...
    def create(self, volume_id: str, source_json: str, name: str | None, created_at: str) -> None: ...
    def get(self, volume_id: str) -> dict[str, Any] | None: ...
    def update_source(self, volume_id: str, source_json: str) -> None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def delete(self, volume_id: str) -> bool: ...


class EvalRepo(Protocol):
    def ensure_schema(self) -> None: ...
    def save_trajectory(self, trajectory: Any, trajectory_json: str) -> str: ...
    def save_metrics(self, run_id: str, tier: str, timestamp: str, metrics_json: str) -> None: ...
    def get_trajectory_json(self, run_id: str) -> str | None: ...
    def list_runs(self, thread_id: str | None = None, limit: int = 50) -> list[dict]: ...
    def get_metrics(self, run_id: str, tier: str | None = None) -> list[dict]: ...


# ---------------------------------------------------------------------------
# Member-Chat — repo protocols
# ---------------------------------------------------------------------------


class MemberRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: MemberRow) -> None: ...
    def get_by_id(self, member_id: str) -> MemberRow | None: ...
    def get_by_name(self, name: str) -> MemberRow | None: ...
    def get_by_email(self, email: str) -> MemberRow | None: ...
    def get_by_mycel_id(self, mycel_id: int) -> MemberRow | None: ...
    def list_all(self) -> list[MemberRow]: ...
    def list_by_type(self, member_type: str) -> list[MemberRow]: ...
    def list_by_owner_user_id(self, owner_user_id: str) -> list[MemberRow]: ...
    def update(self, member_id: str, **fields: Any) -> None: ...
    def increment_entity_seq(self, member_id: str) -> int: ...
    def delete(self, member_id: str) -> None: ...


class ChatRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: ChatRow) -> None: ...
    def get_by_id(self, chat_id: str) -> ChatRow | None: ...
    def delete(self, chat_id: str) -> None: ...


class ThreadRepo(Protocol):
    def close(self) -> None: ...
    def create(self, thread_id: str, member_id: str, sandbox_type: str, cwd: str | None, created_at: float, **extra: Any) -> None: ...
    def get_by_id(self, thread_id: str) -> dict[str, Any] | None: ...
    def get_main_thread(self, member_id: str) -> dict[str, Any] | None: ...
    def get_next_branch_index(self, member_id: str) -> int: ...
    def list_by_member(self, member_id: str) -> list[dict[str, Any]]: ...
    def list_by_owner_user_id(self, owner_user_id: str) -> list[dict[str, Any]]: ...
    def update(self, thread_id: str, **fields: Any) -> None: ...
    def delete(self, thread_id: str) -> None: ...


class ContactRepo(Protocol):
    def close(self) -> None: ...
    def upsert(self, row: ContactRow) -> None: ...
    def get(self, owner_id: str, target_id: str) -> ContactRow | None: ...
    def list_for_user(self, owner_id: str) -> list[ContactRow]: ...
    def delete(self, owner_id: str, target_id: str) -> None: ...


class DeliveryResolver(Protocol):
    """Evaluates delivery strategy for a chat message recipient.

    Checks contact-level block/mute, then chat-level mute, then defaults to DELIVER.
    """

    def resolve(self, recipient_id: str, chat_id: str, sender_id: str, *, is_mentioned: bool = False) -> DeliveryAction: ...


class InviteCodeRepo(Protocol):
    def close(self) -> None: ...
    def generate(self, *, created_by: str | None = None, expires_days: int | None = 7) -> dict: ...
    def get(self, code: str) -> dict | None: ...
    def list_all(self) -> list[dict]: ...
    def use(self, code: str, user_id: str) -> dict | None: ...
    def is_valid(self, code: str) -> bool: ...
    def revoke(self, code: str) -> bool: ...
