from typing import Any

class BeautifulSoup:
    def __init__(self, markup: str, features: str | None = None, **kwargs: Any) -> None: ...
    def find(self, name: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
    def get_text(self, separator: str = ..., strip: bool = ...) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[Any]: ...
