#!/usr/bin/env python3
from __future__ import annotations

import argparse
import secrets
import time
from urllib.parse import urlparse

import jwt


def _port_from_url(url: str) -> str:
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        raise SystemExit(f"--public-url must be an absolute URL: {url}")
    if parsed.port is not None:
        return str(parsed.port)
    if parsed.scheme == "https":
        return "443"
    if parsed.scheme == "http":
        return "80"
    raise SystemExit(f"--public-url must use http or https: {url}")


def _supabase_role_token(role: str, secret: str) -> str:
    now = int(time.time())
    return jwt.encode({"role": role, "iss": "mycel-cli-minimal", "iat": now}, secret, algorithm="HS256")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a local Mycel CLI-minimal compose env.")
    parser.add_argument("--jwt-secret", default=None, help="Supabase/PostgREST JWT secret. Random by default.")
    parser.add_argument("--public-url", default="http://127.0.0.1:8042", help="URL that cel clients should connect to.")
    parser.add_argument("--bind-host", default="127.0.0.1", help="Host address published by docker compose.")
    args = parser.parse_args()

    jwt_secret = args.jwt_secret or secrets.token_urlsafe(48)
    port = _port_from_url(args.public_url)

    print("# Generated by deploy/cli-minimal/generate-env.py")
    print("# Keep this file local; it contains service credentials.")
    print(f"SUPABASE_JWT_SECRET={jwt_secret}")
    print(f"SUPABASE_ANON_KEY={_supabase_role_token('anon', jwt_secret)}")
    print(f"LEON_SUPABASE_SERVICE_ROLE_KEY={_supabase_role_token('service_role', jwt_secret)}")
    print(f"MYCEL_BIND_HOST={args.bind_host}")
    print(f"MYCEL_PORT={port}")
    print(f"MYCEL_PUBLIC_URL={args.public_url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
